EXTERN CreateWindowExA:PROC
EXTERN CreateWindowExW:PROC
EXTERN ShowWindow:PROC
EXTERN GetMessageA:PROC
EXTERN ExitProcess:PROC
EXTERN DispatchMessageA:PROC
EXTERN UpdateWindow:PROC
EXTERN GetLastError:PROC
PUBLIC NEW_CONTROL

CONTROLPROPERTIES STRUCT
    MAINWINDOWHANDLE    QWORD   ?
    WINDOWCLASSNAME     QWORD   ?
    WINDOWNAME          QWORD   ?
    X                   QWORD   ?
    Y                   QWORD   ?
    NWIDTH              QWORD   ?
    NHEIGTH             QWORD   ?
    MAINWINDOWMESSAGEHANDLER QWORD ?
    PARENTHANDLE QWORD ?
CONTROLPROPERTIES ENDS

.DATA
    CONTROL CONTROLPROPERTIES <?>
    WS_CHILDWINDOW EQU 40000000H
    WS_VISIBLE EQU 10000000H
    WS_BORDER EQU 00800000H

.CODE
NEW_CONTROL PROC
    MOV RSI, RCX
    MOV RCX, SIZEOF CONTROLPROPERTIES
    LEA RDI, [CONTROL]
    REP MOVSB
    MOV R15, RSP 
    ;; CREATE CONTROL
    SUB RSP, 5*8+8
    MOV RCX, 00000200H
    MOV RDX, CONTROL.WINDOWCLASSNAME
    MOV R8, CONTROL.WINDOWNAME
    MOV R9, WS_VISIBLE
    XOR R9, 00010000H
    PUSH 0
    PUSH 0
    PUSH 0
    PUSH [CONTROL.PARENTHANDLE]
    PUSH CONTROL.NWIDTH
    PUSH CONTROL.NHEIGTH
    PUSH CONTROL.X
    PUSH CONTROL.Y
    CALL CREATEWINDOWEXA
    CALL GETLASTERROR
    MOV [CONTROL.MAINWINDOWHANDLE], RAX
    MOV RCX, [CONTROL.PARENTHANDLE]
    MOV RCX, [RCX]
    MOV RDX,5
     CHANGEWINDOW:
	    CALL ShowWindow
		 MOV RCX, [CONTROL.PARENTHANDLE]
         MOV RCX,[RCX]
		CALL UpdateWindow
    MOV RSP, R15
    RET

NEW_CONTROL ENDP

END
